default: &default
  # corpid: "corpid"
  # corpsecret: "corpsecret"
  # agentid:  1
# Or if using public account, only need above two line
  # appid: ""
  # secret: ""
  # token: "my_token"
  # access_token: "C:/Users/[username]/wechat_access_token"
  # encrypt_mode: false # if true must fill encoding_aes_key
  # encoding_aes_key:  "my_encoding_aes_key"
  # jsapi_ticket: "C:/Users/[user_name]/wechat_jsapi_ticket"
  appid:    <%= Rails.application.secrets['wechat_appid']   %>
  secret:   <%= Rails.application.secrets['wechat_secret'] %>
  token:    <%= Rails.application.secrets['wechat_token'] %>
  timeout:    30,
  skip_verify_ssl: true
  encrypt_mode: false # if true must fill encoding_aes_key
  # encoding_aes_key:  Rails.application.secrets['wechat_access_token']
  # oauth2_cookie_duration: <%= ENV['WECHAT_OAUTH2_COOKIE_DURATION'] %> # seconds
  # below are save paths for files
  access_token:  <%= "#{Rails.root}/tmp/wechat_access_token" %>
  jsapi_ticket:  <%= "#{Rails.root}/tmp/wechat_jsapi_ticket" %>

production:
  # corpid:     <%= ENV['WECHAT_CORPID'] %>
  # corpsecret: <%= ENV['WECHAT_CORPSECRET'] %>
  # agentid:    <%= ENV['WECHAT_AGENTID'] %>
# Or if using public account, only need above two line
  appid:    <%= Rails.application.secrets['wechat_appid']   %>
  secret:   <%= Rails.application.secrets['wechat_secret'] %>
  token:    <%= Rails.application.secrets['wechat_token'] %>
  timeout:    30,
  skip_verify_ssl: true
  encrypt_mode: false # if true must fill encoding_aes_key
  # encoding_aes_key:  Rails.application.secrets['wechat_access_token']
  # oauth2_cookie_duration: <%= ENV['WECHAT_OAUTH2_COOKIE_DURATION'] %> # seconds
  # below are save paths for files
  access_token:  <%= "#{Rails.root}/tmp/wechat_access_token" %>
  jsapi_ticket:  <%= "#{Rails.root}/tmp/wechat_jsapi_ticket" %>

development:
  <<: *default
  trusted_domain_fullname: "http://your_dev.proxy.qqbrowser.cc"

test:
  <<: *default
